import { StyleSheet } from "react-native";

export default StyleSheet.create({
  mypageContainer: {
    maxWidth: 600,
    margin: 50,
    padding: 20,
    backgroundColor: '#ffffff',
    borderColor: '#ddd',
    borderWidth: 2,
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    fontFamily: 'Arial',
  },
  title: {
    textAlign: 'center',
    marginBottom: 20,
    color: '#333',
    fontSize: 24,
    fontWeight: 'bold',
  },
  infoBox: {
    padding: 20,
    backgroundColor: '#f9f9f9',
    borderColor: '#e6e6e6',
    borderWidth: 1,
    borderRadius: 8,
  },
  editBox: {
    padding: 20,
    backgroundColor: '#f9f9f9',
    borderColor: '#e6e6e6',
    borderWidth: 1,
    borderRadius: 8,
  },
  infoText: {
    marginVertical: 10,
    fontSize: 16,
    color: '#555',
  },
  infoTextStrong: {
    color: '#333',
    fontWeight: 'bold',
  },
  error: {
    textAlign: 'center',
    color: '#d9534f',
    backgroundColor: '#f2dede',
    padding: 10,
    borderColor: '#ebccd1',
    borderWidth: 1,
    borderRadius: 5,
    marginBottom: 20,
  },
  buttonHover: {
    backgroundColor: '#0056b3',
  },
  buttonDisabled: {
    backgroundColor: '#cccccc',
    cursor: 'not-allowed',
  },
  form: {
    display: 'flex',
    flexDirection: 'column',
    gap: 15,
  },
  formInput: {
    width: '100%',
    padding: 10,
    borderColor: '#ccc',
    borderWidth: 1,
    borderRadius: 5,
    fontSize: 16,
    boxSizing: 'border-box',
  },
  saveButton: {
    borderWidth: 1,
    borderRadius: 3,
    borderColor: '#808080',
    backgroundColor: '#ffffff',
    cursor: 'pointer',
    position: 'relative',
    left: 150,
    width: 300,
  },
  editCancelButton: {
    borderWidth: 1,
    borderRadius: 3,
    borderColor: '#808080',
    backgroundColor: '#ffffff',
    cursor: 'pointer',
    position: 'relative',
    left: 150,
    width: 300,
  },
  infoEditButton: {
    borderWidth: 1,
    borderRadius: 3,
    borderColor: '#808080',
    width: 60,
    backgroundColor: '#ffffff',
    cursor: 'pointer',
  },
  logoutButton: {
    borderWidth: 1,
    borderRadius: 3,
    borderColor: '#808080',
    width: 60,
    backgroundColor: '#ffffff',
    cursor: 'pointer',
    marginLeft: 20,
  },
  myPageButtonBox: {
    position: 'relative',
    top: 10,
    left: 420,
  },
});