
import { StyleSheet } from "react-native";

export default StyleSheet.create({
  findInput: {
    width: 230,
    height: 40,
    borderRadius: 5,
    borderWidth: 0,
    backgroundColor: 'rgb(247, 247, 247)',
    boxShadow: '2 2 2 1 rgba(69, 67, 67, 0.2)',
    shadowRadius: 3,
    marginBottom: 5,
  },
  idpwFindPage: {
    height: '70%',
    fontFamily: 'Arial, sans-serif',
    margin: 0,
    padding: 0,
    color: '#333',
    position: 'relative',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f9f9f9',
  },
  idpwFindBox: {
    minWidth: 350,
    height: 280,
    padding: 20,
    backgroundColor: '#ffffff',
    borderColor: '#ddd',
    borderWidth: 2,
    borderRadius: 10,
    boxShadow: '0 4px 6px rgba(0, 0, 0, 0.1)',
    fontFamily: 'Arial, sans-serif',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  idFormButton: {
    position: 'relative',
    width: 60,
    height: 20,
    borderRadius: 5,
    backgroundColor: 'rgb(39, 143, 255)',
    justifyContent:'center',
    alignItems: 'center',
    marginLeft: 80,
    top: 10
  },
  pwFormButton: {
    position: 'relative',
    width: 60,
    height: 20,
    borderRadius: 5,
    backgroundColor: 'rgb(39, 143, 255)',
        justifyContent:'center',
    alignItems: 'center',
    marginLeft: 80,
    top: 20
  },
  pwFindButton: {
    position: 'absolute',
    width: 90,
    height: 20,
    borderRadius: 5,
    backgroundColor: 'rgb(39, 143, 255)',
        justifyContent:'center',
    alignItems: 'center',
    paddingLeft:3,
    top:-15,
    right: -10
  },
  idFindButton: {
    position: 'absolute',
    width: 90,
    height: 20,
    borderRadius: 5,
    backgroundColor: 'rgb(39, 143, 255)',
    justifyContent:'center',
    alignItems: 'center',
    paddingLeft:3,
    top:-15,
    right: -10
  },
  idpwFindResult: {
    width: 250,
    padding: 20,
    backgroundColor: '#e8e8e8',
    borderColor: '#b4b4b4',
    borderWidth: 1,
    borderRadius: 8,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  popupButton: {
    position: 'relative',
    width: 60,
    height: 20,
    borderRadius: 5,
    backgroundColor: 'rgb(39, 143, 255)',
        justifyContent:'center',
    alignItems: 'center',
    paddingLeft:3,
    marginTop: 20
  },
});